name: API Pipeline

on: [push, pull_request]

env:
  CI: true

jobs:
  run:
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: [13, 14]

    steps:
      - name: Clone repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: node --version
      - run: npm --version

      - name: Install npm dependencies
        run: npm --prefix ./api ci

      - name: Run lint
        run: npm --prefix ./api run lint

      - name: Run build
        run: npm --prefix ./api run build

      - name: Run tests
        run: npm --prefix ./api run test -- --maxWorkers=2
